name: Spring-Websocket

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Delete old Docker image
      run: docker image rm harshsrivastav2003/react-image || true

    - name: Build Docker image
      run: docker build -t harshsrivastav2003/socket .

    - name: Push Docker image to Docker Hub
      run: docker push harshsrivastav2003/socket    
    
    - name: stop old container1
      run: sudo docker container stop socket-container-1 || true
    - name: stop old container2
      run: sudo docker container stop socket-container-2 || true
    - name: stop old container3
      run: sudo docker container stop socket-container-3 || true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

      
    - name: Delete old container1 
      run: sudo docker container rm socket-container-1|| true
    - name: Delete old container2 
      run: sudo docker container rm socket-container-2|| true
    - name: Delete old container3 
      run: sudo docker container rm socket-container-3|| true  

      
    - name: Delete old image 
      run:  sudo docker image rm socket|| true

    - name: Build the Docker image
      run: sudo docker build -t socket .
      
   
    - name: Run docker container-1
      run: sudo docker run -d -p 8080:8080 --name socket-container-1 --network=bridge socket sleep infinity| echo "success"
    - name: Run docker container-2
      run: sudo docker run -d -p 9090:8080 --name socket-container-2 --network=bridge socket sleep infinity| echo "success" 
    - name: Run docker container-3
      run: sudo docker run -d -p 8000:8080 --name socket-container-3 --network=bridge socket sleep infinity| echo "success"     
